Resource:
EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    KeyName: my-public-subnet
    ImageId: 'ami-068663a3c619dd892'
    SecurityGroupIds:
      - !Ref InstanceSecurityGroup

InstanceSecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupDescription: Enable SSH access via port 22
    SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0