# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  createinfrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          command: ls -al
      - run:
          command: aws cloudformation deploy --template-file template.yml --stack-name my-stack

# Orchestrate or schedule a set of jobs
workflows:
  testcli:
    jobs:
      - createinfrastructure

