# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  createAWS:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          command: return 1
      - run: 
          name: destoryEnvironment
          when: on_fail
          command: aws cloudformation delete-sack --stack-name my-stack


  createinfrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
          command: ls -al
      - add_ssh_keys:
          fingerprints: [7c:fd:fa:f2:4a:db:a4:c8:69:dc:bf:51:10:4c:c6:14]
      - run:
          name: install ansible
          command: apk add --update ansible
      - run:
          name: Configure Server
          command: ansible-playbook -i inventory main.yml

  smokeTest:
    docker:
      - image: alpine:latest
    steps:
      - run:
          command: apk add --update curl
      - run:
          name: curl google
          command: |
            if curl -s --head "https://google.com" 
            then
              return 0
            else
              return 1
            fi

# Orchestrate or schedule a set of jobs
workflows:
  testcli:
    jobs:
      - createAWS

